### ISSUE TITLE
Possibility of publishing the web version code?

### ISSUE THREAD

**Issue by yhancik** [pafoster/gdir#1]
I'm not sure it's the best place to ask this, but giving it a shot. The web version of gdir is pretty precious for people with a feature phone, and I've recommended it a few times already in the dumbphones subreddit.

But the Directions API has usage limits and possibly a cost for you, so I was wondering if you had considered publishing the source of the web version so other people could also self-host their own version? 

Curious to hear what you think!

**Comment by pafoster** [comment]
Thanks for your interest! The code for the web version is [now available](https://github.com/pafoster/gdir.telae.net).
